apiVersion: v1
kind: Pod
metadata:
  name: gpu-notebook
  labels:
    app: gpu-notebook
spec:
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  containers:
  - name: gpu-notebook
    image: quay.io/mgiessing/opence:1.8.1-jupyter
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
    ports:
    - containerPort: 8888
      name: gpu-notebook
---
apiVersion: v1
kind: Service
metadata:
  name: gpu-notebook
  labels:
    app: gpu-notebook
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 8888
  selector:
    app: gpu-notebook
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: gpu-notebook
  name: gpu-notebook
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: gpu-notebook
