ARG BASE_IMG

FROM ${BASE_IMG}

RUN micromamba install -y -n base \
    onnx \
    onnxruntime \
    numpy \
    scipy \
    pandas \
    scikit-learn \
    skl2onnx \
    lightgbm \
    xgboost \
    opencv \
    wget \
    matplotlib \
    spacy && \
    micromamba clean --all --yes

ENTRYPOINT ["/usr/local/bin/_entrypoint.sh", "python3"]
